"""A chat model that answers from a cassette: the recorded outputs of one real run.

The public demo's recordings are regenerated by running the real graph (real retrieval, real
checks, the real event bus and Agent Lab's real instrumentation) with this model in place of
Claude, so they cost nothing to remake and can't disagree with the code that produced them.
Only the cassettes (demo/cassettes/*.json) ever cost money; scripts/regen_demo.py makes the rest.

Each recorded call is found by a key over what the model was actually asked: the node, the
system text, the messages and the output schema. If the code now asks something the cassette
never recorded, the call raises `StalePrompt` instead of pairing a changed prompt with an old
answer. The fix for that is a new recording, which is a paid model call.

It is a real `BaseChatModel`, so LangChain's callbacks fire exactly as they do for Claude.
`with_structured_output` parses the recorded JSON with the schema itself; it doesn't go through
langchain-anthropic's own parser (the recordings' headers say so).
"""
from __future__ import annotations

import hashlib
import json
import time
from typing import Any

from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.messages import AIMessage, BaseMessage
from langchain_core.outputs import ChatGeneration, ChatResult
from langchain_core.runnables import RunnableLambda
from pydantic import ConfigDict

from .. import redact

CASSETTE_V = "agentlab-cassette/0"
PROVIDER = "anthropic"


class StalePrompt(RuntimeError):
    """The code asked the model something the cassette never recorded."""


def call_key(node: str, system: str | None, messages: list[dict], schema: dict | None) -> str:
    """sha256 over the canonical call, masked with the app's own redaction whatever TRACE_CONTENT
    says, so a key computed from a stored (masked) recording matches the live call."""
    payload = redact.redact({"node": node, "system": system, "messages": messages, "schema": schema})
    return hashlib.sha256(json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
                          .encode("utf-8")).hexdigest()


class ReplayModel(BaseChatModel):
    """Answers each call with the recorded output whose key matches; sleeps the recorded latency
    unless `fast`."""

    model_config = ConfigDict(arbitrary_types_allowed=True)

    cassette: dict
    fast: bool = False

    @property
    def _llm_type(self) -> str:
        return "replay"

    @property
    def model(self) -> str:
        calls = self.cassette.get("calls") or [{}]
        return calls[0].get("model") or "unknown"

    def _get_ls_params(self, stop: list[str] | None = None, **kwargs: Any) -> dict:
        params = super()._get_ls_params(stop=stop, **kwargs)
        params.update(ls_provider=PROVIDER, ls_model_name=self.model)
        return params

    def _find(self, node: str, key: str) -> dict:
        for call in self.cassette.get("calls", []):
            if call["node"] == node and call["key"] == key:
                return call
        raise StalePrompt(f"stale: prompt for {node} changed since {self.cassette.get('recorded', '?')} "
                          f"(cassette {self.cassette.get('scenario', '?')}); re-record it (a paid model call)")

    def _generate(self, messages: list[BaseMessage], stop: list[str] | None = None,
                  run_manager: Any = None, **kwargs: Any) -> ChatResult:
        from ..graph import prompt_parts  # the one reading of a prompt, shared with the live view

        schema = kwargs.get("replay_schema")
        node = (getattr(run_manager, "metadata", None) or {}).get("langgraph_node", "")
        system, parts = prompt_parts(list(messages))
        json_schema = schema.model_json_schema() if hasattr(schema, "model_json_schema") else schema
        call = self._find(node, call_key(node, system, parts, json_schema))
        if not self.fast and call.get("latency_ms"):
            time.sleep(call["latency_ms"] / 1000)
        usage = call.get("usage") or {}
        tokens_in, tokens_out = int(usage.get("input_tokens", 0)), int(usage.get("output_tokens", 0))
        meta = {"model_name": call.get("model") or self.model}
        if call.get("finish_reason"):
            meta["stop_reason"] = call["finish_reason"]
        message = AIMessage(
            content=call["output"],
            usage_metadata={"input_tokens": tokens_in, "output_tokens": tokens_out, "total_tokens": tokens_in + tokens_out,
                            "input_token_details": {"cache_read": int(usage.get("cache_read", 0)),
                                                    "cache_creation": int(usage.get("cache_write", 0))}},
            response_metadata=meta,
        )
        return ChatResult(generations=[ChatGeneration(message=message)])

    def with_structured_output(self, schema: Any, *, include_raw: bool = False, method: str = "json_schema",
                               **kwargs: Any):
        """The recorded JSON, parsed by `schema` (a pydantic model), shaped like LangChain's
        `include_raw=True` result. The schema is bound the way LangChain binds it, so the callbacks
        (and Agent Lab's chat span) see it."""
        bound = self.bind(replay_schema=schema,
                          ls_structured_output_format={"kwargs": {"method": method}, "schema": schema})

        def parse(message: AIMessage) -> Any:
            try:
                parsed, error = schema.model_validate_json(message.content), None
            except Exception as e:  # noqa: BLE001 - shaped like LangChain's own parser
                parsed, error = None, e
            return {"raw": message, "parsed": parsed, "parsing_error": error} if include_raw else parsed

        return bound | RunnableLambda(parse)
